import React, { useState, useEffect } from 'react';
import { Loader2, AlertCircle, FileText, ArrowLeft, Calendar, Activity, ChevronRight, Trash2 } from 'lucide-react';

interface RecommendationsViewProps {
  session: any; // initially passed, can be null or latest
  sessions: any[];
  onSelectSession: (session: any) => void;
  token: string;
  onDeleteSession: (sessionId: string) => void;
}

export const RecommendationsView: React.FC<RecommendationsViewProps> = ({
  session: initialSession,
  sessions,
  onSelectSession,
  token,
  onDeleteSession,
}) => {
  const [selectedSession, setSelectedSession] = useState<any>(null);
  const [recommendation, setRecommendation] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchRecommendation = async (sessionId: string) => {
    setIsLoading(true);
    setError(null);
    try {
      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}/api/recommendations/${sessionId}`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      const data = await res.json();
      if (res.ok) {
        setRecommendation(data.recommendations);
      } else {
        setRecommendation(null);
      }
    } catch (err: any) {
      console.error("Failed to fetch recommendation", err);
      setRecommendation(null);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    if (selectedSession?.session_id) {
      fetchRecommendation(selectedSession.session_id);
    }
  }, [selectedSession?.session_id, token]);

  const handleGenerateRecommendation = async () => {
    if (!selectedSession?.session_id) return;
    setIsGenerating(true);
    setError(null);
    try {
      const genRes = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}/api/recommendations/${selectedSession.session_id}/generate`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (!genRes.ok) {
        const errData = await genRes.json();
        throw new Error(errData.detail || "Generation failed");
      }
      await fetchRecommendation(selectedSession.session_id);
    } catch (err: any) {
      setError(err.message || "Failed to generate AI recommendations.");
    } finally {
      setIsGenerating(false);
    }
  };

  const getSessionValgus = (s: any) => {
    return s?.risk_data?.valgus_angle ?? 
      (s?.risk_data?.biomechanical_efficiency_score 
        ? Math.round((100 - s.risk_data.biomechanical_efficiency_score) * 0.4 + 7.5 * 10) / 10 
        : 12.0);
  };

  const getAngleRiskLabel = (angle: number) => {
    if (angle < 8) return { label: 'Low Risk Range', color: 'text-[#11801c] bg-[#e6f4ea]' };
    if (angle < 15) return { label: 'Moderate Risk Range', color: 'text-[#b35900] bg-[#fff0e6]' };
    return { label: 'Severe Risk Range', color: 'text-[#ba1a1a] bg-[#ffdad6]' };
  };

  const handleDownloadPlan = async () => {
    if (!recommendation || !selectedSession) return;
    const format = localStorage.getItem("downloadFormat") || "pdf";
    const latestValgus = getSessionValgus(selectedSession);
    const riskCat = selectedSession?.risk_data?.risk_category ?? 'Low Risk';
    const angleRisk = getAngleRiskLabel(latestValgus);

    if (format === "txt") {
      let textContent = `MoveIQ BIOMECHANICAL INTERVENTION PLAN
Session ID: ${selectedSession.session_id}
File: ${selectedSession.video_name || 'session.mp4'}
Date: ${selectedSession.created_at ? new Date(selectedSession.created_at).toLocaleDateString() : 'N/A'}
Valgus Angle: ${latestValgus.toFixed(1)}°
Risk Level: ${angleRisk.label}

SUMMARY:
${recommendation.one_line_summary}

`;

      if (recommendation.categories && recommendation.categories.length > 0) {
        recommendation.categories.forEach((cat: any, i: number) => {
          textContent += `${i + 1}. Category: ${cat.category_name.replace(/_/g, ' ')}\n`;
          textContent += `   Explanation: ${cat.explanation}\n`;
          textContent += `   Recommended Exercises:\n`;
          cat.recommended_exercises?.forEach((ex: string) => {
            textContent += `     - ${ex}\n`;
          });
          textContent += `\n`;
        });
      }

      textContent += `WRAP UP:\n${recommendation.wrap_up_summary}\n\nGenerated by MoveIQ AI Sports Science Platform.`;

      const blob = new Blob([textContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `MoveIQ_Intervention_Plan_${(selectedSession.video_name || 'session').replace('.mp4', '')}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    } else {
      try {
        const jsPDF = (await import('jspdf')).default;
        const doc = new jsPDF('p', 'pt', 'a4');
        const margin = 40;
        let y = 50;

        // Title
        doc.setFont("helvetica", "bold");
        doc.setFontSize(20);
        doc.setTextColor(0, 76, 205); // MoveIQ Blue #004ccd
        doc.text("MoveIQ AI Biomechanical Intervention Plan", margin, y);
        y += 30;

        // Metadata
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(67, 70, 84);
        doc.text(`Session: ${selectedSession.video_name || 'session.mp4'}`, margin, y);
        y += 15;
        doc.text(`Date: ${selectedSession.created_at ? new Date(selectedSession.created_at).toLocaleDateString() : 'N/A'}`, margin, y);
        y += 15;
        doc.text(`Measured Valgus Angle: ${latestValgus.toFixed(1)}° (${angleRisk.label})`, margin, y);
        y += 15;
        doc.text(`Overall Risk Category: ${riskCat}`, margin, y);
        y += 30;

        // Separator Line
        doc.setDrawColor(195, 198, 215);
        doc.line(margin, y, 595 - margin, y);
        y += 30;

        // Summary Title
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(25, 27, 35);
        doc.text("AI Insight Summary:", margin, y);
        y += 18;

        // Summary Text wrapping
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(25, 27, 35);
        const summaryLines = doc.splitTextToSize(recommendation.one_line_summary, 595 - 2 * margin);
        doc.text(summaryLines, margin, y);
        y += summaryLines.length * 15 + 25;

        // Prescribed Exercises
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(25, 27, 35);
        doc.text("Prescribed Exercises & Target Interventions:", margin, y);
        y += 20;

        if (recommendation.categories && recommendation.categories.length > 0) {
          recommendation.categories.forEach((cat: any, i: number) => {
            if (y > 750) {
              doc.addPage();
              y = 50;
            }

            // Category Name
            doc.setFont("helvetica", "bold");
            doc.setFontSize(11);
            doc.setTextColor(0, 55, 155);
            doc.text(`${i + 1}. Category: ${cat.category_name.replace(/_/g, ' ').toUpperCase()}`, margin, y);
            y += 15;

            // Explanation
            doc.setFont("helvetica", "italic");
            doc.setFontSize(9.5);
            doc.setTextColor(67, 70, 84);
            const explanationLines = doc.splitTextToSize(cat.explanation, 595 - 2 * margin - 15);
            doc.text(explanationLines, margin + 15, y);
            y += explanationLines.length * 13 + 12;

            // Recommended Exercises
            doc.setFont("helvetica", "bold");
            doc.setFontSize(9.5);
            doc.setTextColor(25, 27, 35);
            doc.text("Exercises:", margin + 15, y);
            y += 12;

            doc.setFont("helvetica", "normal");
            cat.recommended_exercises?.forEach((ex: string) => {
              if (y > 770) {
                doc.addPage();
                y = 50;
              }
              doc.text(`• ${ex}`, margin + 25, y);
              y += 13;
            });
            y += 20;
          });
        }

        // Save PDF
        const fileName = `MoveIQ_Intervention_Plan_${(selectedSession.video_name || 'session').replace('.mp4', '')}.pdf`;
        doc.save(fileName);
      } catch (err) {
        console.error("Failed to generate PDF plan client-side", err);
      }
    }
  };

  // If in list view
  if (!selectedSession) {
    return (
      <div className="max-w-5xl mx-auto space-y-8 text-[#191b23] text-left animate-fadeIn">
        <div>
          <h1 className="text-[32px] font-bold text-[#191b23]">
            AI Recommendations
          </h1>
          <p className="text-[16px] text-[#434654] mt-2 font-medium">
            Select an analyzed session to view or generate personalized AI corrective training recommendations.
          </p>
        </div>

        {sessions.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {sessions.map((s) => {
              const riskCat = s.risk_data?.risk_category || 'Low Risk';
              const healthScore = s.risk_data?.overall_health_score || 100;
              const valgus = getSessionValgus(s);
              
              return (
                <div
                  key={s.session_id}
                  onClick={() => setSelectedSession(s)}
                  className="bg-white border border-[#c3c6d7] rounded-2xl p-5 hover:border-[#004ccd] hover:shadow-md transition-all cursor-pointer flex flex-col justify-between h-56 group relative"
                >
                  <div>
                    {/* Header */}
                    <div className="flex justify-between items-start mb-3">
                      <div className="flex items-center gap-2">
                        <div className="w-10 h-10 rounded-xl bg-[#faf8ff] border border-[#c3c6d7] flex items-center justify-center text-[#004ccd] shrink-0">
                          <FileText className="w-5 h-5" />
                        </div>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            onDeleteSession(s.session_id);
                          }}
                          className="p-1.5 text-[#ba1a1a] hover:bg-[#ffdad6] rounded-lg transition-colors border border-transparent"
                          title="Delete Recommendation Report"
                        >
                          <Trash2 className="w-4.5 h-4.5" />
                        </button>
                      </div>
                      <span className={`px-2.5 py-0.5 rounded text-[10px] font-bold tracking-wider uppercase ${
                        riskCat === 'High Risk' 
                          ? 'bg-[#ffdad6] text-[#ba1a1a]' 
                          : riskCat === 'Medium Risk' || riskCat === 'Moderate Risk'
                          ? 'bg-[#fff0e6] text-[#b35900]'
                          : 'bg-[#e6f4ea] text-[#11801c]'
                      }`}>
                        {riskCat}
                      </span>
                    </div>

                    {/* Content */}
                    <h3 className="font-extrabold text-[16px] text-[#191c1f] group-hover:text-[#004ccd] transition-colors truncate" title={s.video_name}>
                      {s.video_name}
                    </h3>
                    
                    <div className="mt-3 space-y-1.5 text-xs text-[#737687] font-semibold">
                      <div className="flex items-center gap-1.5">
                        <Calendar className="w-3.5 h-3.5 shrink-0" />
                        <span>{s.created_at ? new Date(s.created_at).toLocaleDateString() : 'N/A'}</span>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <Activity className="w-3.5 h-3.5 shrink-0" />
                        <span>Knee Valgus: {valgus.toFixed(1)}°</span>
                      </div>
                    </div>
                  </div>

                  {/* Footer */}
                  <div className="border-t border-[#c3c6d7]/50 pt-3 flex justify-between items-center mt-4">
                    <span className="text-xs font-bold text-[#737687]">
                      Health Score: <span className="text-[#004ccd]">{healthScore}/100</span>
                    </span>
                    <span className="text-xs font-bold text-[#004ccd] flex items-center gap-0.5 group-hover:translate-x-0.5 transition-transform">
                      View Plan <ChevronRight className="w-3.5 h-3.5" />
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center p-16 bg-white border border-[#c3c6d7] rounded-2xl text-center space-y-4 shadow-sm">
            <FileText className="w-12 h-12 text-[#737687]" />
            <div>
              <h3 className="text-[18px] font-bold text-[#191c1f]">No Session History Available</h3>
              <p className="text-sm text-[#434654] mt-1">Upload and analyze biomechanical videos first to receive AI recommendations.</p>
            </div>
          </div>
        )}
      </div>
    );
  }

  const latestValgus = getSessionValgus(selectedSession);
  const angleRisk = getAngleRiskLabel(latestValgus);
  const riskCat = selectedSession?.risk_data?.risk_category ?? 'Low Risk';

  return (
    <div className="max-w-5xl mx-auto space-y-8 text-[#191b23] text-left animate-fadeIn">
      {/* Back Button */}
      <button
        onClick={() => setSelectedSession(null)}
        className="flex items-center gap-2 px-4 py-2 bg-white border border-[#c3c6d7] rounded-xl font-bold text-xs text-[#004ccd] hover:bg-[#faf8ff] transition-colors"
      >
        <ArrowLeft className="w-4 h-4" /> Back to Recommendation Grid
      </button>

      {/* Header */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-[#c3c6d7]/50 pb-6">
        <div>
          <h1 className="text-[28px] font-extrabold text-[#191b23] truncate max-w-lg" title={selectedSession.video_name}>
            AI Plan: {selectedSession.video_name}
          </h1>
          <p className="text-xs text-[#434654] mt-1 font-semibold flex items-center gap-1.5">
            <Calendar className="w-3.5 h-3.5" />
            Analyzed on {selectedSession.created_at ? new Date(selectedSession.created_at).toLocaleDateString() : 'N/A'}
          </p>
        </div>
      </div>

      {isLoading ? (
        <div className="flex flex-col items-center justify-center p-20 bg-white border border-[#c3c6d7] rounded-2xl shadow-sm">
          <Loader2 className="w-8 h-8 text-[#004ccd] animate-spin mb-2" />
          <p className="text-sm font-semibold text-[#434654]">Fetching AI Recommendations...</p>
        </div>
      ) : recommendation ? (
        <>
          {/* AI Insight Summary Card */}
          <div className="bg-white border border-[#c3c6d7] rounded-xl p-6 shadow-sm relative overflow-hidden">
            <div className="flex justify-between items-start mb-4">
              <div className="flex items-center gap-2">
                <span className="material-symbols-outlined text-[#00379b]">
                  neurology
                </span>
                <h2 className="text-[20px] font-bold text-[#191b23]">
                  AI Insight Summary
                </h2>
              </div>
              <span className={`px-3 py-1 rounded text-[11px] font-bold tracking-wider uppercase ${
                riskCat === 'High Risk' 
                  ? 'bg-[#ffdad6] text-[#ba1a1a]' 
                  : riskCat === 'Medium Risk' || riskCat === 'Moderate Risk'
                  ? 'bg-[#fff0e6] text-[#b35900]'
                  : 'bg-[#e6f4ea] text-[#11801c]'
              }`}>
                {riskCat}
              </span>
            </div>

            <p className="text-[16px] text-[#191b23] bg-[#faf8ff] border-l-4 border-[#00379b] p-4 rounded-r-lg font-medium leading-relaxed">
              {recommendation.one_line_summary}
            </p>
          </div>

          {/* Prescribed Exercises Section */}
          <div>
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-[20px] font-bold text-[#191b23]">
                Prescribed Exercises
              </h2>
              <button
                onClick={handleDownloadPlan}
                className="text-[#00379b] text-[13px] font-semibold hover:underline flex items-center gap-1"
              >
                <span className="material-symbols-outlined text-[18px]">
                  download
                </span>
                Export Intervention Plan
              </button>
            </div>

            <div className="space-y-4">
              {recommendation.categories && recommendation.categories.length > 0 ? (
                recommendation.categories.map((cat: any, idx: number) => (
                  <div
                    key={idx}
                    className="bg-white border border-[#c3c6d7] rounded-xl p-6 hover:border-[#00379b] transition-all shadow-sm space-y-4"
                  >
                    <div className="flex items-start gap-4">
                      <div className="w-10 h-10 rounded-full bg-[#f3f3fe] text-[#00379b] font-bold flex items-center justify-center shrink-0 text-[16px]">
                        0{idx + 1}
                      </div>
                      <div className="flex-1">
                        <h3 className="text-[18px] font-bold text-[#191b23] capitalize">
                          {cat.category_name.replace(/_/g, ' ')}
                        </h3>
                        <p className="text-[13px] text-[#434654] mt-2 leading-relaxed bg-[#faf8ff] p-3 rounded-lg border-l-4 border-slate-300">
                          {cat.explanation}
                        </p>
                      </div>
                    </div>

                    <div className="pl-14">
                      <span className="text-[12px] font-bold text-[#191b23] uppercase tracking-wider block mb-2">Recommended Exercises</span>
                      <ul className="space-y-2">
                        {cat.recommended_exercises?.map((ex: string, eIdx: number) => (
                          <li key={eIdx} className="flex items-center gap-2 text-[14px] text-[#191b23] font-medium">
                            <div className="w-1.5 h-1.5 rounded-full bg-[#004ccd]" />
                            {ex}
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                ))
              ) : (
                <div className="p-6 text-center border border-emerald-500/20 bg-emerald-500/10 rounded-xl">
                  <p className="text-[#11801c] font-semibold">Keep up the good work! No major corrective exercises needed right now.</p>
                </div>
              )}
            </div>
          </div>
        </>
      ) : (
        <div className="flex flex-col items-center justify-center p-12 bg-white border border-[#c3c6d7] rounded-2xl text-center space-y-4 shadow-sm">
          <FileText className="w-12 h-12 text-[#737687]" />
          <div>
            <h3 className="text-[18px] font-bold text-[#191b23]">AI Recommendation Not Generated</h3>
            <p className="text-sm text-[#434654] mt-1">Get custom correction plan by launching the biomechanical engine.</p>
          </div>
          {error && (
            <div className="p-3 bg-red-50 border border-red-200 rounded-xl flex items-center gap-2 text-red-700 text-sm font-semibold max-w-md mx-auto">
              <AlertCircle className="w-4 h-4 shrink-0" />
              <span>{error}</span>
            </div>
          )}
          <button
            onClick={handleGenerateRecommendation}
            disabled={isGenerating}
            className="px-6 py-2.5 bg-[#004ccd] hover:bg-[#003da9] text-white text-sm font-bold rounded-xl transition-all flex items-center gap-2 shadow-sm"
          >
            {isGenerating && <Loader2 className="w-4 h-4 animate-spin" />}
            {isGenerating ? "Analyzing Kinematic Frames..." : "Generate AI Recommendation"}
          </button>
        </div>
      )}
    </div>
  );
};
