version: '3.8'

services:
  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sird_backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FRONTEND_URL=http://localhost

    volumes:
      - ./backend/storage:/app/storage

  # React Production Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sird_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
