/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAthletesRouteImport } from './routes/_authenticated/athletes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInjuriesRouteImport } from './routes/_authenticated/injuries'
import { Route as AuthenticatedMyInjuriesRouteImport } from './routes/_authenticated/my-injuries'
import { Route as AuthenticatedMyProfileRouteImport } from './routes/_authenticated/my-profile'
import { Route as AuthenticatedReportBuilderRouteImport } from './routes/_authenticated/report-builder'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSystemRouteImport } from './routes/_authenticated/system'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVideoAnalysisRouteImport } from './routes/_authenticated/video-analysis'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAthletesIdRouteImport } from './routes/_authenticated/athletes.$id'
import { Route as AuthenticatedAthletesNewRouteImport } from './routes/_authenticated/athletes.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAthletesRoute = AuthenticatedAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInjuriesRoute = AuthenticatedInjuriesRouteImport.update({
  id: '/injuries',
  path: '/injuries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyInjuriesRoute = AuthenticatedMyInjuriesRouteImport.update({
  id: '/my-injuries',
  path: '/my-injuries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyProfileRoute = AuthenticatedMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportBuilderRoute =
  AuthenticatedReportBuilderRouteImport.update({
    id: '/report-builder',
    path: '/report-builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemRoute = AuthenticatedSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVideoAnalysisRoute =
  AuthenticatedVideoAnalysisRouteImport.update({
    id: '/video-analysis',
    path: '/video-analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAthletesIdRoute = AuthenticatedAthletesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAthletesRoute,
} as any)
const AuthenticatedAthletesNewRoute =
  AuthenticatedAthletesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAthletesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/athletes': typeof AuthenticatedAthletesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/injuries': typeof AuthenticatedInjuriesRoute
  '/my-injuries': typeof AuthenticatedMyInjuriesRoute
  '/my-profile': typeof AuthenticatedMyProfileRoute
  '/report-builder': typeof AuthenticatedReportBuilderRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/system': typeof AuthenticatedSystemRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/users': typeof AuthenticatedUsersRoute
  '/video-analysis': typeof AuthenticatedVideoAnalysisRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/athletes/new': typeof AuthenticatedAthletesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/athletes': typeof AuthenticatedAthletesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/injuries': typeof AuthenticatedInjuriesRoute
  '/my-injuries': typeof AuthenticatedMyInjuriesRoute
  '/my-profile': typeof AuthenticatedMyProfileRoute
  '/report-builder': typeof AuthenticatedReportBuilderRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/system': typeof AuthenticatedSystemRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/users': typeof AuthenticatedUsersRoute
  '/video-analysis': typeof AuthenticatedVideoAnalysisRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/athletes/new': typeof AuthenticatedAthletesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/athletes': typeof AuthenticatedAthletesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/injuries': typeof AuthenticatedInjuriesRoute
  '/_authenticated/my-injuries': typeof AuthenticatedMyInjuriesRoute
  '/_authenticated/my-profile': typeof AuthenticatedMyProfileRoute
  '/_authenticated/report-builder': typeof AuthenticatedReportBuilderRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/system': typeof AuthenticatedSystemRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/video-analysis': typeof AuthenticatedVideoAnalysisRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/athletes/$id': typeof AuthenticatedAthletesIdRoute
  '/_authenticated/athletes/new': typeof AuthenticatedAthletesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/alerts'
    | '/analysis'
    | '/analytics'
    | '/athletes'
    | '/dashboard'
    | '/injuries'
    | '/my-injuries'
    | '/my-profile'
    | '/report-builder'
    | '/reports'
    | '/settings'
    | '/system'
    | '/upload'
    | '/users'
    | '/video-analysis'
    | '/auth/callback'
    | '/athletes/$id'
    | '/athletes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/alerts'
    | '/analysis'
    | '/analytics'
    | '/athletes'
    | '/dashboard'
    | '/injuries'
    | '/my-injuries'
    | '/my-profile'
    | '/report-builder'
    | '/reports'
    | '/settings'
    | '/system'
    | '/upload'
    | '/users'
    | '/video-analysis'
    | '/auth/callback'
    | '/athletes/$id'
    | '/athletes/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/alerts'
    | '/_authenticated/analysis'
    | '/_authenticated/analytics'
    | '/_authenticated/athletes'
    | '/_authenticated/dashboard'
    | '/_authenticated/injuries'
    | '/_authenticated/my-injuries'
    | '/_authenticated/my-profile'
    | '/_authenticated/report-builder'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/system'
    | '/_authenticated/upload'
    | '/_authenticated/users'
    | '/_authenticated/video-analysis'
    | '/auth/callback'
    | '/_authenticated/athletes/$id'
    | '/_authenticated/athletes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/athletes': {
      id: '/_authenticated/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AuthenticatedAthletesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/injuries': {
      id: '/_authenticated/injuries'
      path: '/injuries'
      fullPath: '/injuries'
      preLoaderRoute: typeof AuthenticatedInjuriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-injuries': {
      id: '/_authenticated/my-injuries'
      path: '/my-injuries'
      fullPath: '/my-injuries'
      preLoaderRoute: typeof AuthenticatedMyInjuriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-profile': {
      id: '/_authenticated/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof AuthenticatedMyProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report-builder': {
      id: '/_authenticated/report-builder'
      path: '/report-builder'
      fullPath: '/report-builder'
      preLoaderRoute: typeof AuthenticatedReportBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system': {
      id: '/_authenticated/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AuthenticatedSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/video-analysis': {
      id: '/_authenticated/video-analysis'
      path: '/video-analysis'
      fullPath: '/video-analysis'
      preLoaderRoute: typeof AuthenticatedVideoAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/athletes/$id': {
      id: '/_authenticated/athletes/$id'
      path: '/$id'
      fullPath: '/athletes/$id'
      preLoaderRoute: typeof AuthenticatedAthletesIdRouteImport
      parentRoute: typeof AuthenticatedAthletesRoute
    }
    '/_authenticated/athletes/new': {
      id: '/_authenticated/athletes/new'
      path: '/new'
      fullPath: '/athletes/new'
      preLoaderRoute: typeof AuthenticatedAthletesNewRouteImport
      parentRoute: typeof AuthenticatedAthletesRoute
    }
  }
}

interface AuthenticatedAthletesRouteChildren {
  AuthenticatedAthletesIdRoute: typeof AuthenticatedAthletesIdRoute
  AuthenticatedAthletesNewRoute: typeof AuthenticatedAthletesNewRoute
}

const AuthenticatedAthletesRouteChildren: AuthenticatedAthletesRouteChildren = {
  AuthenticatedAthletesIdRoute: AuthenticatedAthletesIdRoute,
  AuthenticatedAthletesNewRoute: AuthenticatedAthletesNewRoute,
}

const AuthenticatedAthletesRouteWithChildren =
  AuthenticatedAthletesRoute._addFileChildren(
    AuthenticatedAthletesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAthletesRoute: typeof AuthenticatedAthletesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInjuriesRoute: typeof AuthenticatedInjuriesRoute
  AuthenticatedMyInjuriesRoute: typeof AuthenticatedMyInjuriesRoute
  AuthenticatedMyProfileRoute: typeof AuthenticatedMyProfileRoute
  AuthenticatedReportBuilderRoute: typeof AuthenticatedReportBuilderRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSystemRoute: typeof AuthenticatedSystemRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVideoAnalysisRoute: typeof AuthenticatedVideoAnalysisRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAthletesRoute: AuthenticatedAthletesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInjuriesRoute: AuthenticatedInjuriesRoute,
  AuthenticatedMyInjuriesRoute: AuthenticatedMyInjuriesRoute,
  AuthenticatedMyProfileRoute: AuthenticatedMyProfileRoute,
  AuthenticatedReportBuilderRoute: AuthenticatedReportBuilderRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSystemRoute: AuthenticatedSystemRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVideoAnalysisRoute: AuthenticatedVideoAnalysisRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
