"""add videos and video_frames tables

Revision ID: 603fd1318eea
Revises: 0001_initial_schema
Create Date: 2026-07-19 12:01:56.152184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_video_tables'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_profile_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('running', 'sprinting', 'jumping', 'squatting', 'landing', 'throwing', 'cutting', 'sport_specific_drill', 'other', name='activitytype'), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('annotated_storage_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='videostatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('analyzed_frame_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_athlete_profile_id', 'videos', ['athlete_profile_id'], unique=False)
    op.create_table('video_frames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('pose_detected', sa.Boolean(), nullable=False),
    sa.Column('landmarks', sa.JSON(), nullable=True),
    sa.Column('left_knee_angle', sa.Float(), nullable=True),
    sa.Column('right_knee_angle', sa.Float(), nullable=True),
    sa.Column('left_hip_angle', sa.Float(), nullable=True),
    sa.Column('right_hip_angle', sa.Float(), nullable=True),
    sa.Column('left_elbow_angle', sa.Float(), nullable=True),
    sa.Column('right_elbow_angle', sa.Float(), nullable=True),
    sa.Column('trunk_lean_angle', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_frames_video_id', 'video_frames', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_frames_video_id', table_name='video_frames')
    op.drop_table('video_frames')
    op.drop_index('ix_videos_athlete_profile_id', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
    # NOT auto-generated: dropping a table that uses a plain sa.Enum column
    # does not reliably drop the underlying Postgres ENUM type on its own --
    # verified by hand (upgrade -> downgrade -> upgrade failed with
    # "type already exists" until these two lines were added). Worth knowing
    # if you add more enum-typed tables later: always check downgrade/upgrade
    # actually round-trips cleanly, don't just trust the autogenerated file.
    op.execute("DROP TYPE IF EXISTS videostatus")
    op.execute("DROP TYPE IF EXISTS activitytype")
