"""add risk assessments table and knee deviation angle columns

Revision ID: b0c054e02005
Revises: 0002_video_tables
Create Date: 2026-07-23 04:59:59.449027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_risk_assessments'
down_revision: Union[str, Sequence[str], None] = '0002_video_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_profile_id', sa.UUID(), nullable=False),
    sa.Column('based_on_video_id', sa.UUID(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.Enum('low', 'moderate', 'high', 'critical', name='riskband'), nullable=False),
    sa.Column('biomechanical_score', sa.Float(), nullable=True),
    sa.Column('asymmetry_score', sa.Float(), nullable=True),
    sa.Column('historical_injury_score', sa.Float(), nullable=True),
    sa.Column('training_load_score', sa.Float(), nullable=True),
    sa.Column('fatigue_score', sa.Float(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('data_completeness_warnings', sa.JSON(), nullable=True),
    sa.Column('computed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_profile_id'], ['athlete_profiles.id'], ),
    sa.ForeignKeyConstraint(['based_on_video_id'], ['videos.id'], ),
    sa.ForeignKeyConstraint(['computed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_assessments_athlete_profile_id', 'risk_assessments', ['athlete_profile_id'], unique=False)
    op.add_column('video_frames', sa.Column('left_knee_deviation_angle', sa.Float(), nullable=True))
    op.add_column('video_frames', sa.Column('right_knee_deviation_angle', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_frames', 'right_knee_deviation_angle')
    op.drop_column('video_frames', 'left_knee_deviation_angle')
    op.drop_index('ix_risk_assessments_athlete_profile_id', table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
    # NOT auto-generated: dropping a table with an enum-typed column doesn't
    # reliably drop the underlying Postgres ENUM type on its own -- the same
    # gotcha hit in migration 0002. Always verify upgrade/downgrade actually
    # round-trips before trusting the autogenerated file.
    op.execute("DROP TYPE IF EXISTS riskband")
