/**
 * Corrective recommendation engine (Milestone 3 / spec module 9).
 *
 * Takes an athlete's injury risk profile (from `injury-risk.ts`) and turns
 * it into a concrete, actionable program split into the five areas the
 * project spec calls out:
 *
 *   - Exercise recommendations
 *   - Mobility improvement suggestions
 *   - Strengthening recommendations
 *   - Recovery planning
 *   - Training modification suggestions
 *
 * Like the risk-scoring engine, this is a transparent, rule-based mapping
 * from measured risk components to a small curated exercise library — not
 * a personalized program generated by a trained model. Each item lists the
 * specific finding that triggered it so a physiotherapist/coach can see the
 * reasoning, not just the suggestion.
 */

import type { InjuryRiskProfile, RiskComponents } from "./injury-risk";

export type CorrectiveCategory =
  | "exercise"
  | "mobility"
  | "strengthening"
  | "recovery"
  | "training_modification";

export type CorrectiveItem = {
  id: string;
  title: string;
  detail: string;
  /** What in the athlete's data triggered this suggestion. */
  rationale: string;
  /** Sets/reps/frequency guidance, where applicable (omitted for recovery/training items). */
  prescription?: string;
  priority: "high" | "medium";
};

export type CorrectiveProgram = {
  exercises: CorrectiveItem[];
  mobility: CorrectiveItem[];
  strengthening: CorrectiveItem[];
  recovery: CorrectiveItem[];
  trainingModifications: CorrectiveItem[];
  /** True when nothing crossed a trigger threshold — maintenance-only program. */
  isMaintenanceOnly: boolean;
};

const HIGH = 60; // component score at/above this => high priority items
const MED = 35; // component score at/above this => medium priority items

function priorityFor(score: number): "high" | "medium" | null {
  if (score >= HIGH) return "high";
  if (score >= MED) return "medium";
  return null;
}

/**
 * Builds the full corrective program from an already-computed risk profile.
 * Pure function of `profile.components` and `profile.categoryRisks` — no
 * network/DB access, so it's cheap to call anywhere the profile is already
 * on hand (athlete detail page, per-athlete analysis view, report builder).
 */
export function buildCorrectiveProgram(profile: InjuryRiskProfile): CorrectiveProgram {
  const c = profile.components;
  const exercises: CorrectiveItem[] = [];
  const mobility: CorrectiveItem[] = [];
  const strengthening: CorrectiveItem[] = [];
  const recovery: CorrectiveItem[] = [];
  const trainingModifications: CorrectiveItem[] = [];

  const kneeCategory = profile.categoryRisks.find((r) => r.category === "acl");
  const lowerBackCategory = profile.categoryRisks.find((r) => r.category === "lower_back");
  const hamstringCategory = profile.categoryRisks.find((r) => r.category === "hamstring");
  const ankleCategory = profile.categoryRisks.find((r) => r.category === "ankle_sprain");

  // --- Biomechanical deviation (knee valgus / landing & squat mechanics) ---
  const biomechPriority = priorityFor(c.biomechanicalDeviation);
  if (biomechPriority) {
    exercises.push({
      id: "landing-mechanics-drill",
      title: "Drop-landing & deceleration drill",
      detail:
        "Practice controlled box-drop landings focusing on knees tracking over toes, hips back, and a soft absorbing landing rather than a stiff one.",
      rationale: `Biomechanical deviation score ${c.biomechanicalDeviation}/100 — measured knee/trunk alignment during movement is outside the normal range.`,
      prescription: "3 sets x 6 reps, 2-3x/week, low box height progressing gradually",
      priority: biomechPriority,
    });
    strengthening.push({
      id: "glute-med-activation",
      title: "Glute medius activation (lateral band walks)",
      detail:
        "Targets the hip abductors that control knee alignment during single-leg loading — weak glute med is a common driver of knee valgus.",
      rationale: `Biomechanical deviation score ${c.biomechanicalDeviation}/100, driven primarily by knee alignment during movement.`,
      prescription: "3 sets x 15 steps each direction, 3x/week",
      priority: biomechPriority,
    });
    mobility.push({
      id: "ankle-dorsiflexion-mobility",
      title: "Ankle dorsiflexion mobility (knee-to-wall stretch)",
      detail:
        "Limited ankle dorsiflexion forces compensatory knee-in movement during squats and landings; improving it takes pressure off the knee.",
      rationale: "Restricted ankle mobility is a common contributor to the knee-alignment deviations flagged in this analysis.",
      prescription: "2 sets x 10 reps per side, daily",
      priority: biomechPriority,
    });
  }

  if (kneeCategory && kneeCategory.score >= MED) {
    exercises.push({
      id: "single-leg-squat-technique",
      title: "Single-leg squat technique work",
      detail:
        "Slow, mirror-cued single-leg squats to reps a coach or physio can visually check for knee cave-in, done before it shows up under fatigue or speed.",
      rationale: `ACL injury risk category is elevated (${kneeCategory.score}/100).`,
      prescription: "3 sets x 8 reps per leg, 2x/week",
      priority: priorityFor(kneeCategory.score) ?? "medium",
    });
  }

  // --- Movement asymmetry (left/right imbalance) ---
  const asymmetryPriority = priorityFor(c.movementAsymmetry);
  if (asymmetryPriority) {
    strengthening.push({
      id: "unilateral-strength-block",
      title: "Unilateral strength block (single-leg RDL, step-ups, split squats)",
      detail:
        "Rebuilds strength symmetrically instead of letting the dominant/compensating side keep doing more work, which is what widens left/right imbalance over time.",
      rationale: `Movement asymmetry score ${c.movementAsymmetry}/100 — left/right range-of-motion difference is above the normal range.`,
      prescription: "3 sets x 8-10 reps per side, 2x/week, weaker side first",
      priority: asymmetryPriority,
    });
    exercises.push({
      id: "single-leg-balance-work",
      title: "Single-leg balance & proprioception drills",
      detail:
        "Short daily single-leg balance holds (progressing to unstable surfaces or eyes-closed) retrain the weaker side's stability and movement control.",
      rationale: `Movement asymmetry score ${c.movementAsymmetry}/100.`,
      prescription: "2 sets x 30-45s per leg, daily",
      priority: asymmetryPriority,
    });
  }

  // --- Training load ---
  const loadPriority = priorityFor(c.trainingLoadIndicators);
  if (loadPriority) {
    trainingModifications.push({
      id: "deload-week",
      title: loadPriority === "high" ? "Scheduled deload week" : "Reduce weekly training volume",
      detail:
        loadPriority === "high"
          ? "Cut overall training volume by 40-50% for one full week (keep intensity, drop volume) to let cumulative strain resolve before the next hard block."
          : "Trim volume by roughly 15-20% this week, or swap one high-load session for a technical/skills session at lower intensity.",
      rationale: `Training load indicator ${c.trainingLoadIndicators}/100, based on recorded training load.`,
      priority: loadPriority,
    });
    recovery.push({
      id: "load-recovery-monitoring",
      title: "Daily readiness check-in",
      detail:
        "Brief self-reported soreness/sleep/energy check before each session gives the coaching staff an early signal if load reduction isn't enough.",
      rationale: `Training load indicator ${c.trainingLoadIndicators}/100.`,
      priority: loadPriority,
    });
  }

  // --- Fatigue trend ---
  const fatiguePriority = priorityFor(c.fatigueIndicators);
  if (fatiguePriority) {
    recovery.push({
      id: "sleep-recovery-priority",
      title: "Prioritize sleep and passive recovery",
      detail:
        "Movement quality has been trending down across recent sessions, which tracks with accumulating fatigue rather than a skill or technique problem — recovery, not more drilling, is the fix here.",
      rationale: `Fatigue indicator ${c.fatigueIndicators}/100 — declining movement-quality trend across recent analyses.`,
      prescription: "Target 8+ hours sleep, 1-2 full rest days this week",
      priority: fatiguePriority,
    });
    mobility.push({
      id: "active-recovery-mobility-flow",
      title: "Low-intensity mobility flow (foam rolling + dynamic stretching)",
      detail:
        "10-15 minute low-intensity mobility session on non-training days keeps blood flow up without adding load, supporting recovery between sessions.",
      rationale: `Fatigue indicator ${c.fatigueIndicators}/100.`,
      prescription: "10-15 min, on rest days",
      priority: fatiguePriority,
    });
  }

  // --- Trunk lean / lower back ---
  if (lowerBackCategory && lowerBackCategory.score >= MED) {
    strengthening.push({
      id: "core-anti-extension-work",
      title: "Core anti-extension/anti-rotation work (dead bug, bird dog, plank variations)",
      detail:
        "Builds the trunk stability needed to control forward lean under load, which is what the elevated lower-back risk category is flagging.",
      rationale: `Lower back injury risk category elevated (${lowerBackCategory.score}/100), linked to trunk lean during movement.`,
      prescription: "3 sets x 10 reps (or 30-40s holds), 3x/week",
      priority: priorityFor(lowerBackCategory.score) ?? "medium",
    });
    mobility.push({
      id: "hip-flexor-mobility",
      title: "Hip flexor mobility (kneeling hip flexor stretch)",
      detail:
        "Tight hip flexors pull the pelvis forward and encourage trunk lean during dynamic movement — pairing mobility here with core strengthening addresses both sides of the pattern.",
      rationale: `Lower back injury risk category elevated (${lowerBackCategory.score}/100).`,
      prescription: "2 sets x 30s per side, daily",
      priority: priorityFor(lowerBackCategory.score) ?? "medium",
    });
  }

  // --- Hamstring / ankle categories (training-load driven in this app) ---
  if (hamstringCategory && hamstringCategory.score >= HIGH) {
    strengthening.push({
      id: "nordic-hamstring-curls",
      title: "Nordic hamstring curls",
      detail:
        "Eccentric hamstring strength is one of the best-evidenced ways to reduce hamstring strain risk, particularly under high or rising training load.",
      rationale: `Hamstring injury risk category elevated (${hamstringCategory.score}/100).`,
      prescription: "2-3 sets x 4-6 reps, 1-2x/week (progress slowly — this exercise causes real soreness)",
      priority: "high",
    });
  }
  if (ankleCategory && ankleCategory.score >= HIGH) {
    exercises.push({
      id: "ankle-stability-work",
      title: "Single-leg ankle stability drills",
      detail:
        "Combines the knee-alignment and balance work already flagged with ankle-specific proprioception to reduce sprain risk on cutting/landing movements.",
      rationale: `Ankle sprain risk category elevated (${ankleCategory.score}/100).`,
      prescription: "2 sets x 10 reps per side (multi-directional hops), 2x/week",
      priority: "high",
    });
  }

  // --- Historical injury factors ---
  if (c.historicalInjuryFactors >= MED) {
    recovery.push({
      id: "physio-review-flag",
      title: "Physiotherapist review before increasing load",
      detail:
        "Recorded injury history or an ongoing medical condition means load increases should be cleared by a physiotherapist rather than following the default progression.",
      rationale: `Historical injury factor score ${c.historicalInjuryFactors}/100, based on recorded injury history/medical conditions.`,
      priority: priorityFor(c.historicalInjuryFactors) ?? "medium",
    });
  }

  const isMaintenanceOnly =
    exercises.length === 0 &&
    mobility.length === 0 &&
    strengthening.length === 0 &&
    recovery.length === 0 &&
    trainingModifications.length === 0;

  if (isMaintenanceOnly) {
    exercises.push({
      id: "maintenance-baseline",
      title: "Maintain current training and movement-prep routine",
      detail:
        "No risk factor crossed a trigger threshold. Keep the existing warm-up, strength, and mobility routine as-is and re-check after the next video analysis.",
      rationale: "All risk components are within the normal range.",
      priority: "medium",
    });
  }

  return {
    exercises: sortByPriority(exercises),
    mobility: sortByPriority(mobility),
    strengthening: sortByPriority(strengthening),
    recovery: sortByPriority(recovery),
    trainingModifications: sortByPriority(trainingModifications),
    isMaintenanceOnly,
  };
}

function sortByPriority(items: CorrectiveItem[]): CorrectiveItem[] {
  const rank: Record<CorrectiveItem["priority"], number> = { high: 0, medium: 1 };
  return [...items].sort((a, b) => rank[a.priority] - rank[b.priority]);
}

export const CATEGORY_LABELS: Record<CorrectiveCategory, string> = {
  exercise: "Exercise recommendations",
  mobility: "Mobility improvement",
  strengthening: "Strengthening",
  recovery: "Recovery planning",
  training_modification: "Training modification",
};

/** Total count of corrective items across all categories, for badges/summaries. */
export function totalItemCount(program: CorrectiveProgram): number {
  return (
    program.exercises.length +
    program.mobility.length +
    program.strengthening.length +
    program.recovery.length +
    program.trainingModifications.length
  );
}
