import { useEffect, useState } from "react";
import client from "../api/client";
import { useAuth } from "../api/AuthContext";
import Icon from "../components/Icon";

const EMPTY_PROFILE = { sport_type: "", position: "", age: "", height_cm: "", weight_kg: "", training_load: "", injury_history: "" };

export default function Profile() {
  const { user } = useAuth();
  const [profile, setProfile] = useState(EMPTY_PROFILE);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(user.role === "athlete");
  useEffect(() => { if (user.role !== "athlete") return; client.get("/athletes/me").then(response => setProfile({ ...EMPTY_PROFILE, ...response.data, age: response.data.age ?? "", height_cm: response.data.height_cm ?? "", weight_kg: response.data.weight_kg ?? "" })).catch(() => setError("Profile could not be loaded.")).finally(() => setLoading(false)); }, [user.role]);
  const update = (key, value) => setProfile(current => ({ ...current, [key]: value }));
  const save = async event => { event.preventDefault(); setMessage(""); setError(""); try { const payload = { ...profile, age: profile.age ? Number(profile.age) : null, height_cm: profile.height_cm ? Number(profile.height_cm) : null, weight_kg: profile.weight_kg ? Number(profile.weight_kg) : null }; const response = await client.put("/athletes/me", payload); setProfile(current => ({ ...current, ...response.data })); setMessage("Athlete profile saved."); } catch (err) { setError(err.response?.data?.detail || "Profile could not be saved."); } };
  const initials = user.full_name.split(" ").map(name => name[0]).slice(0, 2).join("").toUpperCase();
  if (loading) return <div className="page-loading"><span className="pulse-dot"/>Loading athlete profile…</div>;
  if (user.role !== "athlete") return <section className="page-enter"><div className="page-heading"><div><span className="eyebrow">ACCOUNT</span><h1>My account</h1><p>Your role-specific access is active and ready to support the team.</p></div></div><div className="account-card panel"><span className="large-avatar">{initials}</span><div><span className="eyebrow">IDENTITY</span><h2>{user.full_name}</h2><p>{user.email}</p><span className="role-tag"><Icon name="shield" size={15}/>{user.role.replaceAll("_", " ")}</span></div><div className="account-stat"><b>Secure</b><span>Role-based access</span></div></div></section>;
  return <section className="page-enter"><div className="page-heading"><div><span className="eyebrow">ATHLETE PROFILE</span><h1>Your training context matters.</h1><p>Keep your sport, training load, and injury history current to give every assessment meaningful context.</p></div></div>{error && <div className="notice-error">{error}</div>}<div className="profile-layout"><aside className="profile-summary"><span className="large-avatar">{initials}</span><h2>{user.full_name}</h2><p>{user.email}</p><div><span>Sport</span><b>{profile.sport_type || "Not set"}</b></div><div><span>Training load</span><b className={`load-chip ${profile.training_load || "none"}`}>{profile.training_load || "Not set"}</b></div><div className="profile-tip"><Icon name="spark" size={17}/><p>Complete profiles create more useful risk and recommendation signals.</p></div></aside><form className="panel profile-form" onSubmit={save}><div className="panel-title"><div><h3>Performance profile</h3><p>Used alongside video biomechanics to personalize your risk score.</p></div><span className="step-number">01</span></div><div className="form-grid two"><label>Sport<input value={profile.sport_type} onChange={event => update("sport_type", event.target.value)} placeholder="e.g. Football"/></label><label>Position / discipline<input value={profile.position} onChange={event => update("position", event.target.value)} placeholder="e.g. Midfielder"/></label><label>Age<input type="number" min="8" max="100" value={profile.age} onChange={event => update("age", event.target.value)} placeholder="e.g. 22"/></label><label>Training load<select value={profile.training_load} onChange={event => update("training_load", event.target.value)}><option value="">Select current load</option><option value="low">Low</option><option value="moderate">Moderate</option><option value="high">High</option></select></label><label>Height (cm)<input type="number" min="80" max="260" value={profile.height_cm} onChange={event => update("height_cm", event.target.value)} placeholder="e.g. 178"/></label><label>Weight (kg)<input type="number" min="20" max="350" value={profile.weight_kg} onChange={event => update("weight_kg", event.target.value)} placeholder="e.g. 72"/></label></div><label>Relevant injury history<textarea rows="5" value={profile.injury_history} onChange={event => update("injury_history", event.target.value)} placeholder="Example: left ankle sprain in 2024, currently pain-free. Include relevant history only."/></label>{message && <div className="notice-success"><Icon name="check" size={17}/>{message}</div>}<button className="primary-button">Save profile <Icon name="check" size={17}/></button></form></div></section>;
}
