REVOKE EXECUTE ON FUNCTION public.role_prefix(public.app_role) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_org_wide(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_access_athlete_row(uuid, uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.can_access_athlete_user(uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.staff_directory() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated, PUBLIC;
GRANT EXECUTE ON FUNCTION public.role_prefix(public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_org_wide(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_access_athlete_row(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_access_athlete_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.staff_directory() TO authenticated;